---
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/de-minimal-rhel8:latest'

dependencies:
  galaxy:
    collections:
      - ansible.eda
  system:
    - pkg-config
    - systemd-devel
    - gcc
    - python39-devel
  python_interpreter:
    package_system: "python39"

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_builder:
    - 'RUN mkdir -p /ansible/playbooks'
#    - 'COPY /Users/benson.ngoy/Code/aap/rulebooks/playbooks/call_cadctl.yaml /ansible/playbooks/call_cadctl.yaml'
