apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pd-entry
  namespace: aap
spec:
  host: pd-entry.apps.bng0y.8dd2.s1.devshift.org
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: activation-job-2-5000
    weight: 100
  wildcardPolicy: None

