---
- name: Listen for events on a webhook
  hosts: all
  execution_strategy: parallel  # with this strategy, the alerts will be handled in //

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: pagerduty
      # sends all pagerduty webhook calls to cadctl
      condition: "1" == "1"
      # condition: event.meta.headers == "PagerDuty-Webhook/V3.0"
      actions:
        - run_job_template:
            name: Demo Job Template
            organization: Default

